using Microsoft.VisualBasic;
using MyAquariumCheck.Models;

namespace MyAquariumCheck;

public partial class ListPage : ContentPage
{
	public ListPage()
	{
        InitializeComponent();

        var items = new List<FishList>
        {
            new FishList { Nome ="Oranda", Descrizione="E' una varietà di pesce rosso e uno dei pochi pesci da acquario che si adatta bene ad un range di temperature dell'acqua comprese tra i 18° ed i 28° gradi, ideale tra i 22° e 26°. Presenta varie colorazioni come arancione, rosso, bianco e rosso, rosso e nero, nero, blu. Presente in diversi tipi di varietà, tra i più comuni troviamo Rosso, Shubunkin, Calico, Fantail, Ryukin, Testa di Leone, Black Moor e Ranchu. Puo raggiungere dimensioni da adulto comprese tra i 12 e 15 cm di lunghezza pertanto richiede acquari di alto litraggio, almeno 80/100 litri. Pesce longevo e resistente in condizioni ideali può vivere anche 20 anni.", imgname="oranda.jpg"},
            new FishList { Nome ="Ramirezi", Descrizione="Appartiene alla famiglia dei ciclidi nani detti Ramirez. Pesce esigente e che richiede cura. Presenta colorazioni vivaci e puo raggiungere una dimensione di lunghezza di 7/9 cm.", imgname="ramirezi.jpg"},
            new FishList { Nome ="Betta", Descrizione="Betta Splendens o anche detto Pesce combattente e un pesce elegante di dimensioni ridotte, puo raggiungere i 6/8 cm per i maschi e 5 cm per le femmine. In gradi di respirare ossigeno direttamente dall'aria tramite un organo detto labirinto. Pesce che non richiede alti litraggi e che non ama molto la compagnia. Le principali varietà sono Plakat, Veiltail,Halfmoon e la Crowntail. Predilige temperature tra i 25° e 28° gradi. Necessità di condizioni specifiche in particolare al PH affinche si possa mantenere in buona salute.", imgname="betta.jpg"},
            new FishList { Nome ="Platy", Descrizione="Piccolo pesce d'acqua dolce della famiglia delle Poeciliidae che può raggiunge di 5 o 6 cm di una lunghezza massima. Molto diffuso tra i pesci da acquario presenta colori vivaci e di facile riproduzione, adatto anche ai neofiti in acquariologia. Presenta molte varietà tra le quali citiamo Corallo, Tiger, High Fin, Red Wag, Yellow Tuxedo e Blue Neon Wagtail.", imgname="platy.jpg"},
            new FishList { Nome ="Discus", Descrizione="Appartenente ai ciclici di acqua dolce presenta un corpo compresso ai fianchi e di forma discoidale da cui poi ne deriva il nome. Presenta colori sgargianti e le dimensioni in adulto si aggirano tra i 15 e 20 cm lunghezza. Preferisce stare in branchi e puo vivere anche 10 anni. Necessità di valori dell'acqua ben definiti e un litraggio elevato vivendo in branchi ed spostandosi in tal maniera.", imgname="discus.jpg"},
            new FishList { Nome ="Corydoras", Descrizione="Pesce di piccole dimensioni che si attesta tra i 3 ed i 15 cm a seconda delle specie. Pesce di acqua dolce da fondale, considerato un pesce spazzino ma necessita a sua volta di cibo specifico pur alimentandosi con quello che trova nel fondo dell'acquario. E' un pesce gregario che ama stare in piccoli gruppi ed in generale presenta colorazioni con variazioni tra il nero ed il marrone chiaro a volte con trame a punti. ", imgname="corydoras.jpg"},
            new FishList { Nome ="Scalare", Descrizione="Scalare o pesce angelo è un pesce tropicale della famiglia dei ciclidi. Necessita valori dell'acquario specifici e presenta spesso un carattere aggressivo e molto territoriale che non gradisce la presenza di altre specie o altri simili. La colorazioni più diffusa e quella grigio tigrata con occhio rosso che gli conferisce un aspetto elegante e minaccioso, ma ci sono anche varianti nere, bianche e blu scuro. Richiede un buon litraggio dato che raggiunge dimensioni di circa 15 cm di lunghezza e 20 cm di altezza. E' uno dei pesci da acquario più conosciuto e non disdegna acquari anche di alte dimensioni.", imgname="scalare.jpg"},
            new FishList { Nome ="Guppy", Descrizione="Pesce di acqua dolce di piccole dimensioni (da 3,5 cm ai massimo 6 delle femmine) molto noto in acquariologia grazie alla facilità di allevamento con la quale si riproduce in maniera molto rapida. Presenta svariate tonalità di colori vivaci soprattutto negli esemplari maschi. E' un pesce adatto ai neofiti che ama stare in branchi. Compagni ideali di questa specie sono i Platy mentre non è consigliata la convivenza con pesci aggressivi con gli Scalari dei quali ne sarebbero preda.", imgname="guppy.jpg"},
            new FishList { Nome ="Neon", Descrizione="Altro pesce estremamente diffuso in acquariologia grazie alla sua livrea sgargiante in genere composta da due strisce orizzontali blu e rossa. originario dell'Amazzonia e un pesce che sta in banchi quindi va inserito sempre in un buon numero. Ama nuotare in branchi numerosi e nascondersi nella vegetazione pertanto predilige acquari lunghi e rigogliosi. Non si riproduce facilmente ma è un pesce abbastanza resistenza che ben si adatta all'acquariologia. Puo essere inserito in compagnia di Platy, Molly e Guppy ma se ne sconsiglia altamente la convivenza con Scali o pesci aggressivi.", imgname="neon.jpg"},
        };

        ListView.ItemsSource= items;  
	}
}