using Microsoft.VisualBasic;
using MyAquariumCheck.Models;

namespace MyAquariumCheck;

public partial class ListPage : ContentPage
{
	public ListPage()
	{
        InitializeComponent();

        var items = new List<FishList>
        {
            new FishList { Nome ="Oranda", Descrizione="E' una varietà di pesce rosso e uno dei pochi pesci da acquario che si adatta bene ad un range di temperature dell'acqua comprese tra i 18° ed i 28° gradi, ideale tra i 22° e 26°. Presenta varie colorazioni come arancione, rosso, bianco e rosso, rosso e nero, nero, blu. Si trova in diversi tipi di varietà, tra i più comuni troviamo Rosso, Shubunkin, Calico, Fantail, Ryukin, Testa di Leone, Black Moor e Ranchu. Può raggiungere dimensioni da adulto comprese tra i 12 e 15 cm di lunghezza pertanto richiede acquari di alto litraggio, almeno 80/100 litri. Pesce longevo e resistente in condizioni ideali può vivere anche 20 anni. Adatto ai neofiti.", imgname="oranda.jpg"},
            new FishList { Nome ="Ramirezi", Descrizione="Appartiene alla famiglia dei ciclidi nani detti Ramirez. E' un pesce molto diffuso in acquariologia ma è un pesce esigente e che richiede cura. Necessita di una temperatura compresa tra i 26° e 30° gradi e predilige fondi sabbiosi che ama esplorare. Presenta colorazioni molto vivaci e può raggiungere una dimensione di lunghezza di 7/9 cm. Richiede un buon litraggio e un allestimento con piante e vegetazione per fornirgli dei nascondigli, non adatto ai neofiti.", imgname="ramirezi.jpg"},
            new FishList { Nome ="Betta", Descrizione="Betta Splendens o anche detto Pesce combattente e un pesce elegante di dimensioni ridotte, puo raggiungere i 6/8 cm per i maschi e 5 cm per le femmine. In grado di respirare ossigeno direttamente dall'aria tramite un organo detto labirinto. Pesce che non richiede alti litraggi anzi se ne cosiglia massimo 30/40 litri con bassa colonna di acqua e che non ama molto la compagnia. Le principali varietà sono Plakat, Veiltail,Halfmoon e la Crowntail. Predilige temperature tra i 25° e 28° gradi. Necessità di condizioni specifiche in particolare al PH affinché si possa mantenere in buona salute.", imgname="betta.jpg"},
            new FishList { Nome ="Platy", Descrizione="Piccolo pesce d'acqua dolce della famiglia delle Poeciliidae che può raggiunge di 5 / 6 cm di una lunghezza massima. Molto diffuso tra i pesci da acquario presenta colori vivaci e si riproduce facilmente, adatto anche ai neofiti in acquariologia. Presenta molte varietà tra le quali citiamo Corallo, Tiger, High Fin, Red Wag, Yellow Tuxedo e Blue Neon Wagtail. La facilita con cui si riproduce porta spesso ad una rapida espansione del banco, va inserito sempre in numero non inferiore a 8/10 unità essendo un pesca da banco.", imgname="platy.jpg"},
            new FishList { Nome ="Discus", Descrizione="Appartenente ai ciclici di acqua dolce e presenta un corpo compresso ai fianchi e di forma discoidale da cui ne deriva il nome. Ha spesso colori sgargianti, striature e macchie e le dimensioni in adulto si aggirano tra i 15 / 20 cm lunghezza. Preferisce stare in banchi e puo vivere anche 10 anni. Necessità di valori dell'acqua ben definiti e un litraggio elevato vivendo in branchi ed spostandosi molto. Non adatto ai neofiti.", imgname="discus.jpg"},
            new FishList { Nome ="Corydoras", Descrizione="Pesce di piccole dimensioni che si attesta tra i 3 ed i 15 cm a seconda delle specie. E' un pesce d'acqua dolce da fondale, considerato uno spazzino ma necessita di cibo specifico pur alimentandosi con quello che trova nel fondo dell'acquario. E' un gregario ed ama stare in piccoli gruppi e in generale presenta colorazioni con variazioni tra il nero ed il marrone chiaro a volte con trame a punti. Adatto ai neofiti popola lo strato basso degli acquari.", imgname="corydoras.jpg"},
            new FishList { Nome ="Scalare", Descrizione="Scalare o Pesce Angelo è un pesce tropicale della famiglia dei ciclidi. Necessita valori dell'acquario specifici e presenta spesso un carattere aggressivo e molto territoriale, non gradisce la presenza di altre specie ne altri simili. La colorazioni più diffusa e quella grigio tigrata con occhio rosso che gli conferisce un aspetto elegante e minaccioso, ma ci sono anche varianti nere, bianche e blu scuro. Richiede un buon litraggio dato che raggiunge dimensioni di circa 15 cm di lunghezza e 20 cm di altezza. E' uno dei pesci da acquario più conosciuto e non disdegna acquari anche di alte dimensioni.", imgname="scalare.jpg"},
            new FishList { Nome ="Guppy", Descrizione="Pesce di acqua dolce di piccole dimensioni (da 3,5 cm dei maschi ai 6 cm delle femmine) molto noto in acquariologia, forse il più noto. Grazie alla facilità di allevamento  si riproduce in maniera molto rapida, aumentando spesso in maniera rapida in numero. Presenta svariate tonalità di colori vivaci soprattutto negli esemplari maschi. E' molto adatto ai neofiti ed ama stare in banchi composti da almeno dieci elementi. Compagni ideali di questa specie sono i Platy o i Molly mentre non è sconsigliata la convivenza con pesci aggressivi come gli Scalari dei quali ne sarebbe preda.", imgname="guppy.jpg"},
            new FishList { Nome ="Neon", Descrizione="Altro pesce estremamente diffuso in acquariologia grazie alla sua livrea sgargiante in genere composta da due strisce orizzontali blu e rossa. Originario dell'Amazzonia e un pesce che sta in banchi quindi va inserito sempre in un buon numero. Ama nuotare in banchi numerosi e nascondersi nella vegetazione pertanto predilige acquari lunghi e rigogliosi. Non si riproduce facilmente ma è un pesce abbastanza resistente che ben si adatta all'acquariologia. Puo essere inserito in compagnia di Platy, Molly e Guppy ma se ne sconsiglia altamente la convivenza con Scalari o altre specie aggressive.", imgname="neon.jpg"},
        };

        ListView.ItemsSource= items;  
	}
}